# Generated by Django 3.2.9 on 2023-03-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycontact',
            name='contact',
        ),
        migrations.AddField(
            model_name='verifycontact',
            name='Email',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('--/--', '--/--'), ('female', 'female'), ('male', 'male')], default='', max_length=255),
        ),
    ]
