# Generated by Django 4.1.7 on 2023-03-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_remove_verifycontact_email_verifycontact_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifycontact",
            name="email",
            field=models.CharField(default="N/A", max_length=40),
        ),
    ]
