# Generated by Django 3.2.9 on 2023-03-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_verifycontact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('google', 'google'), ('contact', 'contact')], default='email', max_length=255),
        ),
    ]
