# Generated by Django 4.1.7 on 2023-03-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timesheet", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CSV",
        ),
    ]
