"""
Django settings for protons project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = 'employee.User'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^3w446h9y_(=e@l06@5lz%c5s2sge#_t=@#6spvwdwc^!u@guk"
EMAIL_BACKEND = 'employee.backends.EmailVerifierBackend'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'employee.apps.EmployeeConfig',
    'manager.apps.ManagerConfig',
    'timesheet.apps.TimesheetConfig',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "django_otp",
    'django_crontab',
    # "djrichtextfield",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "protons.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

REST_FRAMEWORK = {
    "NON_FIELD_ERRORS_KEY": "error",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
}


WSGI_APPLICATION = "protons.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# EMAIL_HOST_USER = 'apikey'
# EMAIL_HOST_PASSWORD = "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"
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_USE_TLS = True
# EMAIL_HOST = "smtp.sendgrid.net"
# EMAIL_PORT = 587

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SEND_SMS_URL = "http://login.yourbulksms.net/api/sendhttp.php"
SMS_AUTH_TOKE = "19486AvtJbijyv61a86d33P15"
SMS_DLT_ID = 1207164121066113664
DEFAULT_FROM_EMAIL = "nirmalchouhan9@gmail.com"
TWILIO_VERIFY_SERVICE_SID = "VA169e34874a5e46251bcf962188515950"
TWILIO_ACCOUNT_SID = "ACca1b449b7670158801c097ac9f7eaa07"
TWILIO_AUTH_TOKEN = "df54d3f4cafbc839b6a3dfb8dba49c7b"


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
SENDGRID_API_KEY = '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'
DEFAULT_FROM_EMAIL = 'kushagra.j@protonshub.in'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = SENDGRID_API_KEY




# EMAIL_HOST_USER = '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' # Set to your SendGrid API key

CRONJOBS = [   ('0 1 1 * *', 'timesheet.management.commands.generate_timesheet_csv'),]
CRONJOBS = [('*/10 * * * * *', 'timesheet.management.commands.test')]